rabbitmq-mqtt:
  image: "rabbitmq"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "admin"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
    - "1883:1883"
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
mysql:
  image: "mysql"
  environment:
    MYSQL_ROOT_PASSWORD: "test"
    MYSQL_DATABASE: "api_sensor"
    MYSQL_USER: "api_sensor_user"
    MYSQL_PASSWORD: "test"
  ports:
    - "3306:3306"


